name: github-action.yaml

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f ./.github/workflows/requirements.txt ]; then pip install -r ./.github/workflows/requirements.txt; fi;
      - name: run script for model
        working-directory: ./code_base/create_model_automatic
        run: |
          python generate_model_from_data_file.py
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "TvarozekRastislav"
          git add .
          git commit -m "Updating the repository GitHub html pages in the docs folder"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true